algoritmo "antecessor e sucessor"

// Faça um algoritmo que receba um número inteiro e imprima na tela seu antecessor e o seu sucessor.

var
    num, antecessor, sucessor: inteiro

inicio

    escreval("Digite um número inteiro:")
    leia(numero)

    antecessor: num - 1
    sucessor: num + 1

    escreval("O antecessor do número ", numero, "é ",antecessor)
    escreval("O sucessor do numero ", numero, "é ", sucessor)

fimalgoritmo
